### ISSUE TITLE
Ingar's NetRadiant site seems to be shutdown.

### ISSUE THREAD

**Issue by password-is-already-taken** [Neverball/neverball-docs#2]
Error: The site that NetRadiant build can be obtained seems to be shut down.

_To Replicate:_

1. Go to this page: https://github.com/Neverball/neverball-docs/blob/master/Setup.md

2. Click the link on step 2 or this link: http://ingar.satgnu.net/gtkradiant/

_Expectation:_
Takes me to site.

_What actually happens:_
The 'Server Not Found' error is shown.

**Comment by ChallengeSY** [comment]
Turned out Ingar moved their services to a new address. I have fixed the broken link, and now the Setup page has the correct address in place.
